set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR msp430)

set(TOOLCHAIN_PREFIX "msp430-elf-")
set(TOOLCHAIN_PATH "/opt/gcc-msp430-none/bin/")
set(TOOLCHAIN_EXT "")

set(CMAKE_C_COMPILER ${TOOLCHAIN_PATH}${TOOLCHAIN_PREFIX}gcc${TOOLCHAIN_EXT})
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PATH}${TOOLCHAIN_PREFIX}g++${TOOLCHAIN_EXT})
set(CMAKE_LINKER ${TOOLCHAIN_PATH}${TOOLCHAIN_PREFIX}ld${TOOLCHAIN_EXT})

set(CMAKE_AR ${TOOLCHAIN_PATH}${TOOLCHAIN_PREFIX}gcc-ar${TOOLCHAIN_EXT})
set(CMAKE_RANLIB ${TOOLCHAIN_PATH}${TOOLCHAIN_PREFIX}gcc-ranlib${TOOLCHAIN_EXT})

set(CMAKE_OBJCOPY ${TOOLCHAIN_PATH}${TOOLCHAIN_PREFIX}objcopy${TOOLCHAIN_EXT}
    CACHE FILEPATH "" FORCE)
set(CMAKE_OBJDUMP ${TOOLCHAIN_PATH}${TOOLCHAIN_PREFIX}objdump${TOOLCHAIN_EXT}
    CACHE FILEPATH "" FORCE)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY )
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY )
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY )
